import re
from datetime import datetime
from io import BytesIO
import pandas as pd
from flask import render_template, request, redirect, url_for, flash, jsonify, send_file
from flask_login import login_required, current_user
from workpulse.decorators import role_required
from workpulse.database import get_db

def _fetch_tasks_for_employee_report(employee_id, date_from, date_to, project_ids=None, category=None):
    db = get_db()
    params = [employee_id, f"{date_from} 00:00", f"{date_to} 23:59"]
    query = '''
        SELECT t.id, t.created_at, t.running_duration, t.title, t.category, t.approval_status, p.id as project_id, p.name as project_name
        FROM tasks t
        JOIN projects p ON t.project_id = p.id
        WHERE t.employee_id = ?
          AND t.status != 'Running'
          AND datetime(t.created_at) BETWEEN ? AND ?
    '''
    if project_ids:
        placeholders = ','.join('?' for _ in project_ids)
        query += f" AND p.id IN ({placeholders})"
        params.extend(project_ids)
    if category:
        query += " AND t.category = ?"
        params.append(category)
    rows = db.execute(query, params).fetchall()
    return [dict(row) for row in rows]

def _fetch_tasks_for_project_report(project_id, date_from, date_to, employee_ids=None, category=None):
    db = get_db()
    params = [f"{date_from} 00:00", f"{date_to} 23:59"]
    query = '''
        SELECT t.id, t.created_at, t.running_duration, t.title, t.category, t.approval_status, u.id as employee_id, u.full_name as employee_name, p.id as project_id, p.name as project_name
        FROM tasks t
        JOIN users u ON t.employee_id = u.id
        LEFT JOIN projects p ON t.project_id = p.id
        WHERE t.status != 'Running'
          AND datetime(t.created_at) BETWEEN ? AND ?
    '''
    if project_id is not None:
        query += " AND p.id = ?"
        params.append(project_id)
    if employee_ids:
        placeholders = ','.join('?' for _ in employee_ids)
        query += f" AND u.id IN ({placeholders})"
        params.extend(employee_ids)
    if category:
        query += " AND t.category = ?"
        params.append(category)
    rows = db.execute(query, params).fetchall()
    return [dict(row) for row in rows]

def _apply_excel_formatting(workbook):
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side, numbers
    header_fill = PatternFill(start_color='FFC000', end_color='FFC000', fill_type='solid')
    bold_font = Font(bold=True)
    thin = Side(style='thin')
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    for ws in workbook.worksheets:
        ws.freeze_panes = ws['A2']
        ws.auto_filter.ref = ws.dimensions
        for cell in ws[1]:
            cell.font = bold_font
            cell.fill = header_fill
            cell.border = border
            cell.alignment = Alignment(horizontal='center')
        for row in ws.iter_rows(min_row=2, max_row=ws.max_row, min_col=1, max_col=ws.max_column):
            for cell in row:
                cell.border = border
                if isinstance(cell.value, (int, float)):
                    cell.number_format = numbers.FORMAT_NUMBER_00
        for col in ws.columns:
            max_len = max((len(str(cell.value)) for cell in col if cell.value), default=0)
            ws.column_dimensions[col[0].column_letter].width = max_len + 2
        for row in ws.iter_rows(min_row=2, max_row=ws.max_row, min_col=1, max_col=1):
            if str(row[0].value).lower() == 'total':
                for c in ws[row[0].row]:
                    c.font = bold_font

def _generate_employee_excel(tasks, employee_name, date_from, date_to, generated_by):
    df = pd.DataFrame(tasks)
    if df.empty:
        df = pd.DataFrame(columns=['Date', 'Project Name', 'Task Title', 'Category', 'Duration (Hours)', 'Approval Status'])
    else:
        df['Duration (Hours)'] = df['running_duration'].apply(lambda s: round(s / 3600.0, 2))
        df['Date'] = df['created_at'].apply(lambda x: x[:10])
        df = df.rename(columns={'project_name': 'Project Name', 'title': 'Task Title', 'category': 'Category', 'approval_status': 'Approval Status'})
        df = df[['Date', 'Project Name', 'Task Title', 'Category', 'Duration (Hours)', 'Approval Status']]
        
    pivot = df.pivot_table(index='Project Name', values='Duration (Hours)', aggfunc='sum', fill_value=0)
    pivot.loc['Total'] = pivot.sum()
    pivot = pivot.reset_index()
    
    out = BytesIO()
    with pd.ExcelWriter(out, engine='openpyxl') as writer:
        df.to_excel(writer, sheet_name='Details', index=False)
        pivot.to_excel(writer, sheet_name='Summary', index=False)
        ws = writer.book.create_sheet('Metadata')
        info = {
            'Report Type': 'Employee Report',
            'Employee': employee_name,
            'Date From': date_from,
            'Date To': date_to,
            'Generated By': generated_by,
            'Generated On': pd.Timestamp.utcnow().strftime('%Y-%m-%d %H:%M:%S')
        }
        for i, (k, v) in enumerate(info.items(), start=1):
            ws.cell(row=i, column=1, value=k)
            ws.cell(row=i, column=2, value=v)
        _apply_excel_formatting(writer.book)
    out.seek(0)
    return out

def _generate_project_excel(tasks, project_name, date_from, date_to, generated_by):
    df = pd.DataFrame(tasks)
    if df.empty:
        df = pd.DataFrame(columns=['Date', 'Employee Name', 'Project Name', 'Task Title', 'Category', 'Duration (Hours)', 'Approval Status'])
    else:
        df['Duration (Hours)'] = df['running_duration'].apply(lambda s: round(s / 3600.0, 2))
        df['Date'] = df['created_at'].apply(lambda x: x[:10])
        df = df.rename(columns={'employee_name': 'Employee Name', 'project_name': 'Project Name', 'title': 'Task Title', 'category': 'Category', 'approval_status': 'Approval Status'})
        df = df[['Date', 'Employee Name', 'Project Name', 'Task Title', 'Category', 'Duration (Hours)', 'Approval Status']]
        
    pivot = df.pivot_table(index='Employee Name', columns='Project Name', values='Duration (Hours)', aggfunc='sum', fill_value=0)
    pivot['Total'] = pivot.sum(axis=1)
    total_row = pivot.sum(axis=0)
    total_row.name = 'Total'
    details_df = pd.concat([pivot, pd.DataFrame([total_row])])
    
    per_employee = pivot[pivot.columns.drop('Total')].sum(axis=1)
    per_employee = per_employee.round(2)
    summary_df = pd.DataFrame({
        'Employee': per_employee.index,
        'Total Hours': per_employee.values
    })
    grand_total = per_employee.sum().round(2)
    summary_df = pd.concat([summary_df, pd.DataFrame({'Employee': ['Grand Total'], 'Total Hours': [grand_total]})], ignore_index=True)
    
    out = BytesIO()
    with pd.ExcelWriter(out, engine='openpyxl') as writer:
        details_df.to_excel(writer, sheet_name='Details')
        ws = writer.book.create_sheet('Summary')
        info = {
            'Report Type': 'Project Report',
            'Project': project_name if project_name else 'All Projects',
            'Date From': date_from,
            'Date To': date_to,
            'Generated By': generated_by,
            'Generated On': pd.Timestamp.utcnow().strftime('%Y-%m-%d %H:%M:%S')
        }
        r = 1
        for k, v in info.items():
            ws.cell(row=r, column=1, value=k)
            ws.cell(row=r, column=2, value=v)
            r += 1
        table_start = r + 1
        ws.cell(row=table_start, column=1, value='Employee')
        ws.cell(row=table_start, column=2, value='Total Hours')
        for i, rec in enumerate(summary_df.itertuples(index=False), start=1):
            ws.cell(row=table_start + i, column=1, value=rec.Employee)
            ws.cell(row=table_start + i, column=2, value=rec[1])
        _apply_excel_formatting(writer.book)
    out.seek(0)
    return out

def register_reports_routes(app):
    @app.route('/hr/reports')
    @role_required('HR')
    def hr_reports_page():
        db = get_db()
        employees = db.execute("SELECT id, full_name FROM users WHERE role = 'Employee' ORDER BY full_name").fetchall()
        projects = db.execute("SELECT id, name FROM projects ORDER BY name").fetchall()
        return render_template('hr/hr_reports.html', employees=employees, projects=projects)

    @app.route('/hr/export', methods=['POST'])
    @role_required('HR')
    def hr_export():
        payload = request.get_json()
        if not payload:
            return jsonify({'error': 'Invalid request'}), 400
        report_type = payload.get('type')
        date_from = payload.get('date_from')
        date_to = payload.get('date_to')
        category = payload.get('category')
        if not report_type or not date_from or not date_to:
            return jsonify({'error': 'Missing required parameters'}), 400
        generated_by = current_user.full_name or current_user.username
        
        if report_type == 'employee':
            employee_id = payload.get('employee_id')
            if not employee_id:
                return jsonify({'error': 'Employee ID required'}), 400
            emp = get_db().execute('SELECT full_name FROM users WHERE id = ?', (employee_id,)).fetchone()
            if not emp:
                return jsonify({'error': 'Employee not found'}), 404
            rows = _fetch_tasks_for_employee_report(employee_id, date_from, date_to, payload.get('project_ids'), category)
            excel_io = _generate_employee_excel(rows, emp['full_name'], date_from, date_to, generated_by)
            sanitized_name = re.sub(r'[^A-Za-z0-9]+', '_', emp['full_name']).strip('_')
            filename = f"{sanitized_name}_{date_from}_{date_to}.xlsx"
        elif report_type == 'project':
            project_id = payload.get('project_id')
            project_name = None
            if project_id:
                proj = get_db().execute('SELECT name FROM projects WHERE id = ?', (project_id,)).fetchone()
                if not proj:
                    return jsonify({'error': 'Project not found'}), 404
                project_name = proj['name']
            rows = _fetch_tasks_for_project_report(project_id, date_from, date_to, category=category)
            excel_io = _generate_project_excel(rows, project_name, date_from, date_to, generated_by)
            if project_name:
                sanitized_proj = re.sub(r'[^A-Za-z0-9]+', '_', project_name).strip('_')
            else:
                sanitized_proj = 'all_projects'
            filename = f"{sanitized_proj}_{date_from}_{date_to}.xlsx"
        else:
            return jsonify({'error': 'Invalid report type'}), 400
            
        return send_file(
            excel_io,
            as_attachment=True,
            download_name=filename,
            mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )

    @app.route('/hr/reports/print')
    @role_required('HR')
    def hr_reports_print():
        report_type = request.args.get('type')
        date_from = request.args.get('date_from')
        date_to = request.args.get('date_to')
        category = request.args.get('category')
        
        if not report_type or not date_from or not date_to:
            flash('Missing report parameters.', 'danger')
            return redirect(url_for('hr_reports_page'))
            
        db = get_db()
        rows = []
        title_label = ""
        
        if report_type == 'employee':
            employee_id = request.args.get('employee_id')
            if not employee_id:
                flash('Employee required.', 'danger')
                return redirect(url_for('hr_reports_page'))
            emp = db.execute('SELECT full_name FROM users WHERE id = ?', (employee_id,)).fetchone()
            if not emp:
                flash('Employee not found.', 'danger')
                return redirect(url_for('hr_reports_page'))
            title_label = f"Employee Report: {emp['full_name']}"
            project_ids = request.args.getlist('project_ids')
            rows = _fetch_tasks_for_employee_report(employee_id, date_from, date_to, project_ids, category)
        elif report_type == 'project':
            project_id = request.args.get('project_id')
            project_name = "All Projects"
            if project_id and project_id != 'all':
                proj = db.execute('SELECT name FROM projects WHERE id = ?', (project_id,)).fetchone()
                if proj:
                    project_name = proj['name']
                project_id = int(project_id)
            else:
                project_id = None
            title_label = f"Project Report: {project_name}"
            rows = _fetch_tasks_for_project_report(project_id, date_from, date_to, category=category)
            
        total_seconds = sum(r['running_duration'] for r in rows)
        total_hours = round(total_seconds / 3600.0, 2)
        
        pivot_rows = []
        pivot_cols = []
        pivot_col_totals = {}
        pivot_grand_total = {'worked': 0, 'allocated': 0, 'has_unlimited': False}
        
        if rows:
            employees_set = {}
            projects_set = {}
            for r in rows:
                emp_name = r.get('employee_name') or db.execute('SELECT full_name FROM users WHERE id = ?', (r.get('employee_id') or employee_id,)).fetchone()['full_name']
                emp_id = r.get('employee_id') or int(employee_id)
                proj_name = r['project_name']
                proj_id = r['project_id']
                
                employees_set[emp_id] = emp_name
                projects_set[proj_id] = proj_name
                
            for p_id, p_name in projects_set.items():
                pivot_cols.append({'id': p_id, 'name': p_name})
                
            for emp_id, emp_name in employees_set.items():
                row_cells = {}
                row_total_worked = 0
                row_total_allocated = 0
                row_has_unlimited = False
                
                for p_id in projects_set:
                    work_row = db.execute('''
                        SELECT COALESCE(SUM(running_duration), 0) AS total_dur
                        FROM tasks
                        WHERE employee_id = ? AND project_id = ? AND status != 'Running'
                          AND datetime(created_at) BETWEEN ? AND ?
                    ''', (emp_id, p_id, f"{date_from} 00:00", f"{date_to} 23:59")).fetchone()
                    
                    worked_hours = work_row['total_dur'] / 3600.0
                    
                    alloc_row = db.execute('''
                        SELECT allocated_hours
                        FROM employee_projects
                        WHERE employee_id = ? AND project_id = ?
                    ''', (emp_id, p_id)).fetchone()
                    
                    allocated_hours = alloc_row['allocated_hours'] if alloc_row else 0
                    
                    if worked_hours > 0 or allocated_hours > 0:
                        row_cells[p_id] = {
                            'worked': worked_hours,
                            'allocated': allocated_hours
                        }
                        row_total_worked += worked_hours
                        row_total_allocated += allocated_hours
                        if allocated_hours == 0:
                            row_has_unlimited = True
                            
                        if p_id not in pivot_col_totals:
                            pivot_col_totals[p_id] = {'worked': 0, 'allocated': 0, 'has_unlimited': False}
                        pivot_col_totals[p_id]['worked'] += worked_hours
                        pivot_col_totals[p_id]['allocated'] += allocated_hours
                        if allocated_hours == 0:
                            pivot_col_totals[p_id]['has_unlimited'] = True
                            
                pivot_rows.append({
                    'employee_id': emp_id,
                    'employee_name': emp_name,
                    'cells': row_cells,
                    'total': {
                        'worked': row_total_worked,
                        'allocated': row_total_allocated,
                        'has_unlimited': row_has_unlimited
                    }
                })
                
                pivot_grand_total['worked'] += row_total_worked
                pivot_grand_total['allocated'] += row_total_allocated
                if row_has_unlimited:
                    pivot_grand_total['has_unlimited'] = True
                    
        return render_template(
            'print/print_report.html',
            report_type=report_type,
            date_from=date_from,
            date_to=date_to,
            generated_by=current_user.full_name or current_user.username,
            generated_on=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            title_label=title_label,
            total_hours=total_hours,
            rows=rows,
            pivot_rows=pivot_rows,
            pivot_cols=pivot_cols,
            pivot_col_totals=pivot_col_totals,
            pivot_grand_total=pivot_grand_total
        )
